### ISSUE TITLE
start.sh script needs access to awscli credentials - what type of access?

### ISSUE THREAD

**Issue by lfrancois** [trackit/trackit2-home#60]
What type of permission do we need to get the system up and running? I didn't find anything about it in the documentation.
```
===> starting trackit
Traceback (most recent call last):
  File "./trackit2/scripts/awsenv", line 31, in <module>
    main(profile, cmd)
  File "./trackit2/scripts/awsenv", line 16, in main
    profile_config = get_profile_config(profile)
  File "./trackit2/scripts/awsenv", line 13, in get_profile_config
    return c[profile]
  File "/usr/lib/python3.5/configparser.py", line 956, in __getitem__
    raise KeyError(key)
KeyError: 'default'
```

**Comment by schubev** [comment]
It should work fine with just the following permission :
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AssumeRole",
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "*"
        }
    ]
}
```

**Comment by schubev** [comment]
Also when using AWS ElasticSearch you need to ensure the database policy allows the user or role.

**Comment by lfrancois** [comment]
https://github.com/trackit/trackit/pull/62
